services:
  mongo:
    image: mongo:4.4
    container_name: mongo-apothecary
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend-apothecary
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://admin:password@mongo-apothecary:27017/apothecarydb?authSource=admin
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: frontend-apothecary
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    user: root # Running as root to avoid permission issues
    depends_on:
      - backend

volumes:
  mongo_data:
